#Tomcat端口号
server:
  port: 8888
#数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    password: root
    username: root
#mybatis整合
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.lxr.springbootwebmybatismysql.pojo